export const DORMANT_GOAL_MIN_AGE_HOURS = 24;
export const INITIATIVE_COOLDOWN_HOURS = 24;
export const MAX_OPEN_TASKS_BEFORE_SUPPRESS = 12;
export const MAX_CREATED_TASKS_PER_RUN = 1;
export const MAX_CREATED_TASKS_PER_DAY = 2;
export const MAX_CREATED_TASKS_PER_HOUR = 10;
