import { describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  assertPathInHiveWorkspace,
  assertPathInTaskImageDirectory,
  detectImageMetadata,
  resolveTaskImageDirectory,
  storeTaskImage,
} from "@/work-products/image-storage";

const ONE_BY_ONE_PNG =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=";

describe("image work product storage", () => {
  it("stores generated PNGs under the task image directory", async () => {
    const workspace = fs.mkdtempSync(path.join(os.tmpdir(), "hw-image-workspace-"));
    try {
      const stored = await storeTaskImage({
        hiveWorkspacePath: workspace,
        taskId: "task-123",
        imageBase64: ONE_BY_ONE_PNG,
        fileStem: "concept",
      });

      expect(stored.filePath).toBe(path.join(workspace, "task-123", "images", "concept.png"));
      expect(stored.mimeType).toBe("image/png");
      expect(stored.width).toBe(1);
      expect(stored.height).toBe(1);
      expect(fs.existsSync(stored.filePath)).toBe(true);
    } finally {
      fs.rmSync(workspace, { recursive: true, force: true });
    }
  });

  it("rejects task image paths that escape the hive workspace", () => {
    expect(() => resolveTaskImageDirectory({ hiveWorkspacePath: "/tmp/hive", taskId: "../other" }))
      .toThrow(/escaped/);
    expect(() => assertPathInHiveWorkspace("/tmp/other/task/images/x.png", "/tmp/hive"))
      .toThrow(/outside/);
    expect(() => assertPathInTaskImageDirectory({
      filePath: "/tmp/hive/other-task/images/x.png",
      hiveWorkspacePath: "/tmp/hive",
      taskId: "task-123",
    })).toThrow(/task images/);
  });

  it("reads PNG dimensions from generated bytes", () => {
    const metadata = detectImageMetadata(Buffer.from(ONE_BY_ONE_PNG, "base64"));
    expect(metadata).toEqual({ mimeType: "image/png", width: 1, height: 1 });
  });
});
